services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcashe:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./Services/Catalog/
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


